package com.farmlens.anarai.data.remote

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ForumPost(
    @SerialName("id")
    val id: String = "", // UUID generated by Supabase
    @SerialName("author_name")
    val authorName: String,
    @SerialName("content")
    val content: String,
    @SerialName("created_at")
    val createdAt: String? = null, // Handled by Supabase automatically
    @SerialName("replies")
    val replies: Int = 0
)
